#!/usr/bin/env node

'use strict';

// Script includes
const fs = require('fs');
const el = require('elasticlunr');
const jsdom = require('jsdom');
const recursive = require('recursive-readdir');
const crypto = require('crypto');
const optionParser = require('command-line-args');
const path = require('path');

const VERSION = '0.1';
const DESCRIPTION = 'Script to build the "elasticlunr" search index.'
const SCRIPT_NAME = path.basename(process.argv[1]);

/**
 * Calculates the md5 hash of a string and returns the
 * result as an integer.
 */
function hashString(str) {
    var md5 = crypto.createHash('md5');
    var hex_digest = md5.update(str).digest('hex');
    // Convert to integer
    return parseInt(hex_digest, 16) % 49979687;
}

const optionParams = [
    {name: 'index-dir', alias: 'd', type: String, defaultOption: true},
    {name: 'ignore', alias: 'i', type: String, multiple: true},
    {name: 'output', alias: 'o', type: String, defaultValue: './index.json'},
    {name: 'version', alias: 'v', type: Boolean},
    {name: 'verbose', alias: 'V', type: Boolean},
    {name: 'help', alias: 'h', type: Boolean}
];

const options = optionParser(optionParams);

if (options.help)
{
    console.log(SCRIPT_NAME + ' - ' + DESCRIPTION + '\n');
    console.log(
        'Usage: ' + SCRIPT_NAME + ' INDEX-DIR [--ignore FILE1 FILE2 --output OUT-FILE --verbose]'
    );
}
else if (options.version)
{
    console.log(process.argv[0] + ' - v' + VERSION);
}
else
{
    // Ignore non-html files.
    var ignore = ['*.js', '*.css', '*.xml', '*.jpg', '*.JPG'];

    // Create the index schema.
    var index = el(function () {
        this.addField('title'),
        this.addField('body'),
        this.addField('description'),
        this.addField('url'),
        this.setRef('id')
    });

    if (options.ignore)
    {
        ignore = ignore.concat(options.ignore);
    }

    recursive(options['index-dir'], ignore, function (err, files) {
        if (err)
        {
            console.log(err);
            return;
        }
        for (var file of files)
        {
            var html = fs.readFileSync(file, 'utf-8');
            // Parse the DOM.
            var document = jsdom.jsdom(html);
            var meta_title = document.querySelector('meta[property="og:title"]');
            var meta_description = document.querySelector('meta[name="description"]');
            var article = document.querySelector('article');

            // Only select pages with a title and article section.
            if (meta_title && article)
            {
                if (options.verbose)
                {
                    console.log("Indexing: " + file);
                }
                var doc = {
                    title: meta_title.content,
                    body: article.textContent,
                    description: meta_description.content,
                    url: file.replace(new RegExp('^' + options['index-dir']), ''),
                    id: hashString(file)
                };
                index.addDoc(doc);
            }
        }

        // Serialise and write the index.
        var out = index.toJSON();

        // Remove the body field from the documentStore to decrease the size of the index.
        for (var id in out.documentStore.docs)
        {
            delete out.documentStore.docs[id].body;
        }

        if (options.verbose)
        {
            console.log("Serialising to: " + options.output)
        }
        fs.writeFileSync(options.output, JSON.stringify(out), 'utf-8');

        if (options.verbose)
        {
            console.log('done');
        }
        process.exit();
    });
}
